[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fastapi_user_auth"
authors = [
    { name = "Atomi", email = "1456417373@qq.com" },
]
maintainers = [
    { name = "Atomi", email = "1456417373@qq.com" },
]
description = "fastapi-amis-admin is a high-performance, efficient and easily extensible FastAPI admin framework. Inspired by Django-admin, and has as many powerful functions as Django-admin. "
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version"]
keywords = [
    "fastapi",
    "fastapi-user-auth",
    "fastapi-amis-admin",
    "fastapi-auth",
    "sqlmodel",
]
classifiers = [
    "Framework :: FastAPI",
    "Environment :: Web Environment",
    "Topic :: System :: Systems Administration",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "fastapi-amis-admin",
    "email-validator==1.1.3",
    "passlib==1.7.4",
    "bcrypt",
]



[project.urls]
Documentation = "http://docs.amis.work/"
Source = "https://github.com/amisadmin/fastapi-user-auth"

[project.optional-dependencies]
test = [
    "pytest >=6.2.4,<7.0.0",
    "pytest-asyncio",
    "aiosqlite",
    "jose==1.0.0",
    "python-jose==3.3.0",
]
jwt = [
    "jose==1.0.0",
    "python-jose==3.3.0",
]
redis = ["aioredis"]
db = []
dev = [
    "jinja2 >=2.11.2,<4.0.0",
    "aiosqlite",
    "aioredis",
    "uvicorn[standard] >=0.12.0,<0.16.0",
]
all = [
    "jinja2 >=2.11.2,<4.0.0",
    "uvicorn[standard] >=0.12.0,<0.16.0",
]